# Generated by Django 6.0.4 on 2026-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField()),
                ("last_name", models.CharField(blank=True, null=True)),
                ("patronymic", models.CharField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField()),
            ],
        ),
    ]
