# Generated by Django 6.0.4 on 2026-04-16 20:06

from django.db import migrations


def generate_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Role.objects.get_or_create(role_name="user")
    Role.objects.get_or_create(role_name="admin")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_role_alter_user_email_rolepermission_usertoken"),
    ]

    operations = [migrations.RunPython(generate_roles)]
