# Generated by Django 6.0.4 on 2026-04-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20260416_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="users.role",
            ),
        ),
    ]
