# Generated by Django 6.0.4 on 2026-04-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_role_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_name", models.CharField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="resourse",
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="resourse_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.resource",
            ),
        ),
    ]
