# Generated by Django 6.0.4 on 2026-04-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_resource_remove_rolepermission_resourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="resourse_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.resource"
            ),
        ),
    ]
