# Generated by Django 6.0.4 on 2026-04-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_rolepermission_resourse_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rolepermission",
            old_name="resourse_id",
            new_name="resourсe",
        ),
        migrations.RenameField(
            model_name="rolepermission",
            old_name="role_id",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="role_id",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="usertoken",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("resourсe", "role")},
        ),
        migrations.AddField(
            model_name="role",
            name="default_permission_level",
            field=models.IntegerField(
                choices=[
                    (0, "No access"),
                    (1, "Read only"),
                    (2, "Read, Write, Update"),
                    (3, "Read, Write, Update, Delete"),
                    (4, "Admin access level"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="access_level",
            field=models.IntegerField(
                choices=[
                    (0, "No access"),
                    (1, "Read only"),
                    (2, "Read, Write, Update"),
                    (3, "Read, Write, Update, Delete"),
                    (4, "Admin access level"),
                ],
                default=3,
            ),
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="can_update",
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.IntegerField(
                        choices=[
                            (0, "No access"),
                            (1, "Read only"),
                            (2, "Read, Write, Update"),
                            (3, "Read, Write, Update, Delete"),
                            (4, "Admin access level"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "resourсe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.resource"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("resourсe", "user")},
            },
        ),
    ]
