# Generated by Django 6.0.4 on 2026-04-19 11:12

from django.db import migrations


def change_admin(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    admin = Role.objects.get(role_name="admin")
    admin.default_permission_level = 4
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_resourse_id_rolepermission_resourсe_and_more"),
    ]

    operations = [
        migrations.RunPython(change_admin),
    ]
