# Generated by Django 6.0.4 on 2026-04-19 11:49

from django.db import migrations


def add_resource(apps, schema_editor):
    Resource = apps.get_model("users", "Resource")
    current_user_actions = Resource.objects.get_or_create(
        resource_name="current_user_actions"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20260419_1112"),
    ]

    operations = [migrations.RunPython(add_resource)]
