# Generated by Django 6.0.4 on 2026-04-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20260419_1149"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpermission",
            old_name="resourсe",
            new_name="resource",
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together={("resource", "user")},
        ),
    ]
