# Generated by Django 6.0.4 on 2026-04-19 14:13

from django.db import migrations


def add_admin(apps, schema_editor):
    Resource = apps.get_model("users", "User")
    current_user_actions = Resource.objects.get_or_create(
        first_name="Администратор",
        email="admin@gmail.com",
        password="Ruslan10",
        role_id=2,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_resourсe_userpermission_resource_and_more"),
    ]

    operations = [migrations.RunPython(add_admin)]
