# Generated by Django 6.0.4 on 2026-04-19 14:22

from django.db import migrations


def del_admin(apps, schema_editor):
    Resource = apps.get_model("users", "User")
    current_user_actions = Resource.objects.filter(
        email="admin@gmail.com",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_auto_20260419_1413"),
    ]

    operations = [migrations.RunPython(del_admin)]
