# Generated by Django 6.0.4 on 2026-04-19 14:24

from django.db import migrations
from django.contrib.auth.hashers import make_password


def add_admin(apps, schema_editor):
    Resource = apps.get_model("users", "User")
    hashed_password = make_password("Ruslan10")
    current_user_actions = Resource.objects.get_or_create(
        first_name="Администратор",
        email="admin@gmail.com",
        password=hashed_password,
        role_id=2,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20260419_1422"),
    ]

    operations = [migrations.RunPython(add_admin)]
