# Generated by Django 6.0.4 on 2026-04-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20260419_1424"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rolepermission",
            old_name="resourсe",
            new_name="resource",
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("resource", "role")},
        ),
    ]
